# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "agent-cfn"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "agent-cfn"
region = "us-east-1"
parameter_overrides = "AgentName=\"tnobe-agent\" AgentDescription=\"Bedrock Agent from CloudFormation\" AgentInstruction=\"あなたは優秀なAIアシスタントです。\nユーザーからの質問や指示に対して、以下の手順で適切な回答を提供してください。 \n1.ユーザーの依頼内容を注意深く読み、その内容が以下のどのカテゴリーに該当するか判断してください。 \n  a) AnyCompany社の最新情報に関する質問 \n  b) 一般的な知識に関する質問 \n  c) ナレッジベース内の情報への問い合わせ \n2.依頼内容が一般的な知識に関する質問であると判断した場合、あなたが持つ幅広い知識に基づいて、的確で分かりやすい回答を作成してください。 \n3.依頼内容がナレッジベース内の情報への問い合わせであると判断した場合、ナレッジベースに格納されているデータを検索し、関連する情報を抽出して、ユーザーの質問に対する最適な回答を作成してください。 \n4.依頼内容がAnyCompany社の最新情報に関する質問であると判断した場合、専用のfunctionを実行して最新情報を取得し、ユーザーに提供してください。また回答の最後にURLを「■参照元: <url>」と出力してください。 \n5.回答する際は、ユーザーの知識レベルや関心に合わせて、技術的な詳細の量を調整するなど、わかりやすく親しみやすい言葉づかいを心がけてください。 \n以上の手順に従って、ユーザーの期待に応える高品質なアシスタントサービスを提供してください。\n\" ModelId=\"anthropic.claude-3-haiku-20240307-v1:0\" KnowledgeBaseId=\"ZA7IT0HHLV\" KnowledgeBaseDescription=\"Bedrock Agent from CloudFormation\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
